baseURL = ""
RelativeURLs=true
languageCode = "zh-cn"
theme = "kitab"
title = "amaki's novels"

disableKinds = ["taxonomy", "taxonomyTerm"]
pluralizelisttitles = false

[params]
  author = "Yrr0r"
  description = "Sample"
  dateFormat = "2006-01-02"
  footer1 = "Awesome Books"
  footer2 = ":)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true